### ISSUE TITLE
Upgrading to GF 2.5.10.1 causes a "deprecated" error for GFAddOn::settings_save

### ISSUE THREAD

**Issue by bennemann** [GFExcel/gf-entries-in-excel#101]
`Deprecated: GFAddOn::settings_save is deprecated since version 2.5! Use the \Gravity_Forms\Gravity_Forms\Settings\Fields\Button class to add a save button to your form instead. in /var/www/html/gv-sites/gv/wp-includes/functions.php on line 5211`

This is breaking the form settings page for GravityExport lite.

This issue can be reproduced by accessing GravityExport Lite settings for any form on https://debug.gravityview.co/

Here's a direct link to one:
https://debug.gravityview.co/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=gf-entries-in-excel&id=50

Tested with GFExport Lite v1.9.2

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1643167687/37152

**Comment by bennemann** [comment]
Yes, the deprecated error shows up because `WP_DEBUG` is set to `true`. 

However, this is not just about the error showing up. The whole settings page seems to be broken(inputs not showing), even when debug mode is off:

![image](https://user-images.githubusercontent.com/5726194/135459468-5e02bf76-99e8-482c-b96d-29b7eae9eda5.png)

**Comment by doekenorg** [comment]
This support topic seems to be the same problem: https://wordpress.org/support/topic/issue-in-the-settings/#post-14925012
