### ISSUE TITLE
Gravity Perks Live Preview (show hidden) not working

### ISSUE THREAD

**Issue by doekenorg** [GFExcel/gf-entries-in-excel#105]
When the plugin is active, the perk `Live Preview` does not work correctly when applying `Show hidden`. It will simply not show these fields. Somehow the plugin interferes with the retrieving of the form and field objects.

I traced it back to:

https://github.com/GFExcel/gf-entries-in-excel/blob/358e3083d3bfec2e79a8fc3297ad9eb626b3a8aa/src/GFExcelAdmin.php#L254-L267

In the `init()` function we're already retrieving the form object. Which is why it fails further on; something to with caching probably. 

I propose a `getRepository()` function to retrieve the repository only when it is needed; and add it to the micro cache then. 
Might also be enough to move this to `init_admin()` as I'm not sure this is needed on the frontend.

**Comment by guilamu** [comment]
I have nothing meaningful to add, so thanks a lot for your support Doeke!

**Comment by doekenorg** [comment]
Resolved by #113
