### ISSUE TITLE
Nested form values are raw

### ISSUE THREAD

**Issue by doekenorg** [GFExcel/gf-entries-in-excel#123]
When exporting a form with a nested form, the values for these forms are raw. They are not retrieved through their proper fields, making the output somewhat undesirable when using a `Product field` for instance. 

The values should at least be retrieved through their field. But it would be better if the nested forms were also piped through the transformer class. This way there are a lot more hooks available to customize the output.

**Comment by doekenorg** [comment]
In response to https://wordpress.org/support/topic/create-seperated-row-from-nested-form-content. Post update on (and close) this ticket after resolving.

**Comment by rafaehlers** [comment]
Also, make sure that the future code could allow this:

>The multiple rows in the excel spreadsheet for the child records - does the parent header record also print on the multiple rows or does it only print on the first row ? If it only prints one header parent record is there any php code I could add to my functions.php to print a parent record with each of the child records ?

Example:  

![image](https://user-images.githubusercontent.com/1222472/165841862-0250e986-a48e-4153-afc9-a94f6e6e638b.png)

In the future the `xxx` would have the same information replicated for every row:

![image](https://user-images.githubusercontent.com/1222472/165842060-ec92e65f-d886-467f-ae15-9a8f634dc239.png)


From: https://secure.helpscout.net/conversation/1861963004/40938/

**Comment by doekenorg** [comment]
@rafaehlers This is tricky business, as multiple rows are merged together. If there is only one column with multiple values, it could work. But when having two for example, those rows are merged to avoid too many almost empty rows.

What do we do with the empty fields on those columns?

<img width="544" alt="Schermafbeelding 2022-04-28 om 22 54 12" src="https://user-images.githubusercontent.com/529515/165844004-b174e6e1-e703-45b6-988a-fa6ef443d8de.png">

In this example both `Full name` and `Choices` are multiple fields. We can repeat the last values, but that would make the output very weird IMHO.

**Comment by rafaehlers** [comment]
Right! Good point.
