### ISSUE TITLE
Transposed PDF exports have extra columns

### ISSUE THREAD

**Issue by doekenorg** [GFExcel/gf-entries-in-excel#125]
If you have a form with 5 columns, and 1 entry; and you transpose the data; you should have 2 columns and 5 rows. 
But you will get at least 5 columns, 3 being empty. This is because the `PHPExcelRenderer` calculated the column width based on the amount of columns. But that doesn't take transposing into account.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1824871488/40384
