### ISSUE TITLE
Add date_updated entry meta to the list of fields to be exported

### ISSUE THREAD

**Issue by rafaehlers** [GFExcel/gf-entries-in-excel#131]
![image](https://user-images.githubusercontent.com/1222472/175388276-bb11a8ea-f07a-4855-a41f-7267060ce278.png)

![image](https://user-images.githubusercontent.com/1222472/175388354-72d11b44-68fe-47ed-826c-511f340b5211.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1927919012/42043

**Comment by doekenorg** [comment]
@rafaehlers This is also resolved in 1.11.2. Closing issue
