### ISSUE TITLE
Filters with `in` and `not in` don't work.

### ISSUE THREAD

**Issue by doekenorg** [GFExcel/gf-entries-in-excel#133]
When applying a `IN` or `NOT IN` filter to the url, the results are not filtered.

eg. `?filter=id:in:20,30` will not work, while `?filter=id:20;id:30;any` *will* work. 

Problem is that the comma separated list should be exploded into an array. The query builder from GF doesn't understand it otherwise. 

This might not work in versions prior to 2.4 of GravityForms. Not really sure if we need to support that though.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1940166813/42324

**Comment by doekenorg** [comment]
@rafaehlers this is fixed in 1.11.2. Closing this issue.
