### ISSUE TITLE
Last 7 days? 

### ISSUE THREAD

**Issue by BenPicard** [GFExcel/gf-entries-in-excel#88]
Hi,

Is it possible to extract the data using a value to get only the new values of the last 7 days?

Thank you,
Ben

**Comment by doekenorg** [comment]
Hi @BenPicard, for support questions like this you are better of on the WordPress [plugin page](https://wordpress.org/support/plugin/gf-entries-in-excel/). This way others may also benefit from these questions. Please reopen your question there. I'll try to whip up some code in the mean time. Thank you.

**Comment by doekenorg** [comment]
I might as well drop the answer here, but still opening a new topic on the support forum is appreciated. 

A filter hook like this added to your `functions.php` should do the trick. This will look for any entries created after 7 days ago, effectively return only those results. You can simply append `?last_week` to you download url, and it should work. 

```php
// Filter to add `?last_week` to the download url to only retrieve the data from the last 7 days.
add_filter('gfexcel_output_search_criteria', function (array $search_criteria): array {
    if (isset($_GET['last_week'])) {
        $search_criteria['field_filters'][] = [
            'key' => 'date_created',
            'operator' => '>=',
            'value' => date_i18n('Y-m-d 00:00:00', strtotime('-7 days'))
        ];
    }

    return $search_criteria;
});
```
