### ISSUE TITLE
Support GP Nested Forms

### ISSUE THREAD

**Issue by rafaehlers** [GFExcel/gf-entries-in-excel#98]
Requested by a user: https://secure.helpscout.net/conversation/1626525302/36836

**Comment by doekenorg** [comment]
https://gist.github.com/doekenorg/48157d53a1f8b9c1b09ace85448519ed

**Comment by doekenorg** [comment]
The difficulty is in the fact that every entry can have multiple entries form the nested form.  

I think it would be the nicest if we just added the columns to the output and suffix them with the name of the wrapping field. 

`Nested Field (Wrapper) | Nested Field 2 (Wrapper)`

And that every entry get's its own row (when that is available in pro).

**Comment by doekenorg** [comment]
This seems to mimic the original esport the best, according to the docs.

One piece or feedback there is the option to export these rows to a separate sheet. 

With CSV's this isn't possible of course, but excel can do this. Seems like a nice +1 to have. Would require some reference to the original row, and setting a sheet for the field.

**Comment by doekenorg** [comment]
Resolved in #113
