### ISSUE TITLE
phpoffice/phpspreadsheet has security advisories

### ISSUE THREAD

**Issue by jachinfrancke** [GFExcel/gf-entries-in-excel#99]
Hi, could you upgrade the phpoffice/phpspreadsheet dependency to the latest version? It is now fixed to 1.12.0 but that version (and versions up to 1.15.0) has  security advisories (see https://packagist.org/packages/phpoffice/phpspreadsheet for info).

**Comment by jachinfrancke** [comment]
Sorry, found my answer here #84

**Comment by mrcasual** [comment]
In case someone else comes across this issue, I'll note that the XXS and XXE vulnerabilities found in earlier versions do not apply to how PhpSpreadsheet is used by the plugin. We are neither parsing XML files nor converting spreadsheets to HTML.
